package hibernate.entity;
// Generated 19 oct. 2017 10:57:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Produits generated by hbm2java
 */
public class Produits  implements java.io.Serializable {


     private Integer idProduit;
     private String designation;
     private double prix;
     private Integer qteStockee;
     private String photo;
     private Set ligcdeses = new HashSet(0);

    public Produits() {
    }

	
    public Produits(String designation, double prix) {
        this.designation = designation;
        this.prix = prix;
    }
    public Produits(String designation, double prix, Integer qteStockee, String photo, Set ligcdeses) {
       this.designation = designation;
       this.prix = prix;
       this.qteStockee = qteStockee;
       this.photo = photo;
       this.ligcdeses = ligcdeses;
    }
   
    public Integer getIdProduit() {
        return this.idProduit;
    }
    
    public void setIdProduit(Integer idProduit) {
        this.idProduit = idProduit;
    }
    public String getDesignation() {
        return this.designation;
    }
    
    public void setDesignation(String designation) {
        this.designation = designation;
    }
    public double getPrix() {
        return this.prix;
    }
    
    public void setPrix(double prix) {
        this.prix = prix;
    }
    public Integer getQteStockee() {
        return this.qteStockee;
    }
    
    public void setQteStockee(Integer qteStockee) {
        this.qteStockee = qteStockee;
    }
    public String getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(String photo) {
        this.photo = photo;
    }
    public Set getLigcdeses() {
        return this.ligcdeses;
    }
    
    public void setLigcdeses(Set ligcdeses) {
        this.ligcdeses = ligcdeses;
    }




}


